version: '3.8'
services:
  postgres:
    image: postgres:18.1
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: unitalks_db
      POSTGRES_USER: unitalks_admin
      POSTGRES_PASSWORD: c9_n32ub!31_1k_ld_Rs
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - pgdata:/var/lib/postgresql/data

  user_service:
    build: ./backend/user_service
      context: .
      dockerfile: Dockerfile
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgresql://unitalks_admin:c9_n32ub!31_1k_ld_Rs@db:5432/unitalks_db
      SECRET_KEY: ​SECRET_KEY
    depends_on: [postgres]

  post_service:
    build: ./backend/post_service
      context: .
      dockerfile: Dockerfile
    ports: ["8001:8001"]
    environment:
      DATABASE_URL: postgresql://unitalks_admin:c9_n32ub!31_1k_ld_Rs@db:5432/unitalks_db
      SECRET_KEY: ​SECRET_KEY
    depends_on: [postgres]

  frontend:
    build: ./frontend
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80" 
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports: ["80:80"]
    volumes: ["./nginx/default.conf:/etc/nginx/conf.d/default.conf"]
    depends_on: [user_service, post_service]

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.0
    ports: ["10051:10051"]
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: unitalks_admin
      POSTGRES_PASSWORD: c9_n32ub!31_1k_ld_Rs
    depends_on: [postgres]

  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    volumes: ["grafana_data:/var/lib/grafana"]

volumes:
  pgdata:

  grafana_data:


